### ISSUE TITLE
Consider introducing a Spring Boot starter.

### ISSUE THREAD

**Issue by martin-lindstrom** [swedenconnect/credentials-support#61]
Spring has introduced the SSL Bundles concept, see https://docs.spring.io/spring-boot/reference/features/ssl.html#features.ssl.

We should consider making a similar solution for pre-registering `PkiCredential` instances.

Suppose that an application has a configuration something like

```
credentials:
  bundle:
    mycred:
      keystore:
        location: file:/etc/config/keys.jks
        password: secret
        type: JKS
      key:
        alias: tls
        password: secret

foo:
  ...
  credential-bundle: mycred
```

This would be a better way to configure credentials, that later could be referred with the bundle name.
